/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTableNumberRouteImport } from './routes/t.$tableNumber'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPedidosOnlineRouteImport } from './routes/_authenticated/pedidos-online'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedLlevarRouteImport } from './routes/_authenticated/llevar'
import { Route as AuthenticatedKioskoRouteImport } from './routes/_authenticated/kiosko'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated/kds'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedDomiciliosRouteImport } from './routes/_authenticated/domicilios'
import { Route as AuthenticatedDomicilioRouteImport } from './routes/_authenticated/domicilio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedAyudaRouteImport } from './routes/_authenticated/ayuda'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedMenuProductosRouteImport } from './routes/_authenticated/menu/productos'
import { Route as AuthenticatedMenuModificadoresRouteImport } from './routes/_authenticated/menu/modificadores'
import { Route as AuthenticatedMenuInsumosRouteImport } from './routes/_authenticated/menu/insumos'
import { Route as AuthenticatedMenuCategoriasRouteImport } from './routes/_authenticated/menu/categorias'

const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableNumberRoute = TTableNumberRouteImport.update({
  id: '/t/$tableNumber',
  path: '/t/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosOnlineRoute =
  AuthenticatedPedidosOnlineRouteImport.update({
    id: '/pedidos-online',
    path: '/pedidos-online',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLlevarRoute = AuthenticatedLlevarRouteImport.update({
  id: '/llevar',
  path: '/llevar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKioskoRoute = AuthenticatedKioskoRouteImport.update({
  id: '/kiosko',
  path: '/kiosko',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomiciliosRoute = AuthenticatedDomiciliosRouteImport.update({
  id: '/domicilios',
  path: '/domicilios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomicilioRoute = AuthenticatedDomicilioRouteImport.update({
  id: '/domicilio',
  path: '/domicilio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAyudaRoute = AuthenticatedAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuProductosRoute =
  AuthenticatedMenuProductosRouteImport.update({
    id: '/menu/productos',
    path: '/menu/productos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuModificadoresRoute =
  AuthenticatedMenuModificadoresRouteImport.update({
    id: '/menu/modificadores',
    path: '/menu/modificadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuInsumosRoute =
  AuthenticatedMenuInsumosRouteImport.update({
    id: '/menu/insumos',
    path: '/menu/insumos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuCategoriasRoute =
  AuthenticatedMenuCategoriasRouteImport.update({
    id: '/menu/categorias',
    path: '/menu/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/menu': typeof MenuRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/ayuda': typeof AuthenticatedAyudaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domicilio': typeof AuthenticatedDomicilioRoute
  '/domicilios': typeof AuthenticatedDomiciliosRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/kiosko': typeof AuthenticatedKioskoRoute
  '/llevar': typeof AuthenticatedLlevarRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/pos': typeof AuthenticatedPosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/t/$tableNumber': typeof TTableNumberRoute
  '/menu/categorias': typeof AuthenticatedMenuCategoriasRoute
  '/menu/insumos': typeof AuthenticatedMenuInsumosRoute
  '/menu/modificadores': typeof AuthenticatedMenuModificadoresRoute
  '/menu/productos': typeof AuthenticatedMenuProductosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/menu': typeof MenuRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/ayuda': typeof AuthenticatedAyudaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domicilio': typeof AuthenticatedDomicilioRoute
  '/domicilios': typeof AuthenticatedDomiciliosRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/kiosko': typeof AuthenticatedKioskoRoute
  '/llevar': typeof AuthenticatedLlevarRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/pos': typeof AuthenticatedPosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/t/$tableNumber': typeof TTableNumberRoute
  '/menu/categorias': typeof AuthenticatedMenuCategoriasRoute
  '/menu/insumos': typeof AuthenticatedMenuInsumosRoute
  '/menu/modificadores': typeof AuthenticatedMenuModificadoresRoute
  '/menu/productos': typeof AuthenticatedMenuProductosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kiosk': typeof KioskRoute
  '/menu': typeof MenuRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/ayuda': typeof AuthenticatedAyudaRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domicilio': typeof AuthenticatedDomicilioRoute
  '/_authenticated/domicilios': typeof AuthenticatedDomiciliosRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/kiosko': typeof AuthenticatedKioskoRoute
  '/_authenticated/llevar': typeof AuthenticatedLlevarRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
  '/t/$tableNumber': typeof TTableNumberRoute
  '/_authenticated/menu/categorias': typeof AuthenticatedMenuCategoriasRoute
  '/_authenticated/menu/insumos': typeof AuthenticatedMenuInsumosRoute
  '/_authenticated/menu/modificadores': typeof AuthenticatedMenuModificadoresRoute
  '/_authenticated/menu/productos': typeof AuthenticatedMenuProductosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/menu'
    | '/ajustes'
    | '/ayuda'
    | '/caja'
    | '/clientes'
    | '/crm'
    | '/dashboard'
    | '/domicilio'
    | '/domicilios'
    | '/inventario'
    | '/kds'
    | '/kiosko'
    | '/llevar'
    | '/mesas'
    | '/pedidos-online'
    | '/pos'
    | '/usuarios'
    | '/ventas'
    | '/t/$tableNumber'
    | '/menu/categorias'
    | '/menu/insumos'
    | '/menu/modificadores'
    | '/menu/productos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kiosk'
    | '/menu'
    | '/ajustes'
    | '/ayuda'
    | '/caja'
    | '/clientes'
    | '/crm'
    | '/dashboard'
    | '/domicilio'
    | '/domicilios'
    | '/inventario'
    | '/kds'
    | '/kiosko'
    | '/llevar'
    | '/mesas'
    | '/pedidos-online'
    | '/pos'
    | '/usuarios'
    | '/ventas'
    | '/t/$tableNumber'
    | '/menu/categorias'
    | '/menu/insumos'
    | '/menu/modificadores'
    | '/menu/productos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kiosk'
    | '/menu'
    | '/_authenticated/ajustes'
    | '/_authenticated/ayuda'
    | '/_authenticated/caja'
    | '/_authenticated/clientes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/domicilio'
    | '/_authenticated/domicilios'
    | '/_authenticated/inventario'
    | '/_authenticated/kds'
    | '/_authenticated/kiosko'
    | '/_authenticated/llevar'
    | '/_authenticated/mesas'
    | '/_authenticated/pedidos-online'
    | '/_authenticated/pos'
    | '/_authenticated/usuarios'
    | '/_authenticated/ventas'
    | '/t/$tableNumber'
    | '/_authenticated/menu/categorias'
    | '/_authenticated/menu/insumos'
    | '/_authenticated/menu/modificadores'
    | '/_authenticated/menu/productos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KioskRoute: typeof KioskRoute
  MenuRoute: typeof MenuRoute
  TTableNumberRoute: typeof TTableNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableNumber': {
      id: '/t/$tableNumber'
      path: '/t/$tableNumber'
      fullPath: '/t/$tableNumber'
      preLoaderRoute: typeof TTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos-online': {
      id: '/_authenticated/pedidos-online'
      path: '/pedidos-online'
      fullPath: '/pedidos-online'
      preLoaderRoute: typeof AuthenticatedPedidosOnlineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/llevar': {
      id: '/_authenticated/llevar'
      path: '/llevar'
      fullPath: '/llevar'
      preLoaderRoute: typeof AuthenticatedLlevarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kiosko': {
      id: '/_authenticated/kiosko'
      path: '/kiosko'
      fullPath: '/kiosko'
      preLoaderRoute: typeof AuthenticatedKioskoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domicilios': {
      id: '/_authenticated/domicilios'
      path: '/domicilios'
      fullPath: '/domicilios'
      preLoaderRoute: typeof AuthenticatedDomiciliosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domicilio': {
      id: '/_authenticated/domicilio'
      path: '/domicilio'
      fullPath: '/domicilio'
      preLoaderRoute: typeof AuthenticatedDomicilioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ayuda': {
      id: '/_authenticated/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AuthenticatedAyudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/productos': {
      id: '/_authenticated/menu/productos'
      path: '/menu/productos'
      fullPath: '/menu/productos'
      preLoaderRoute: typeof AuthenticatedMenuProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/modificadores': {
      id: '/_authenticated/menu/modificadores'
      path: '/menu/modificadores'
      fullPath: '/menu/modificadores'
      preLoaderRoute: typeof AuthenticatedMenuModificadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/insumos': {
      id: '/_authenticated/menu/insumos'
      path: '/menu/insumos'
      fullPath: '/menu/insumos'
      preLoaderRoute: typeof AuthenticatedMenuInsumosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/categorias': {
      id: '/_authenticated/menu/categorias'
      path: '/menu/categorias'
      fullPath: '/menu/categorias'
      preLoaderRoute: typeof AuthenticatedMenuCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedAyudaRoute: typeof AuthenticatedAyudaRoute
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomicilioRoute: typeof AuthenticatedDomicilioRoute
  AuthenticatedDomiciliosRoute: typeof AuthenticatedDomiciliosRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedKioskoRoute: typeof AuthenticatedKioskoRoute
  AuthenticatedLlevarRoute: typeof AuthenticatedLlevarRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedPedidosOnlineRoute: typeof AuthenticatedPedidosOnlineRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
  AuthenticatedMenuCategoriasRoute: typeof AuthenticatedMenuCategoriasRoute
  AuthenticatedMenuInsumosRoute: typeof AuthenticatedMenuInsumosRoute
  AuthenticatedMenuModificadoresRoute: typeof AuthenticatedMenuModificadoresRoute
  AuthenticatedMenuProductosRoute: typeof AuthenticatedMenuProductosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedAyudaRoute: AuthenticatedAyudaRoute,
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomicilioRoute: AuthenticatedDomicilioRoute,
  AuthenticatedDomiciliosRoute: AuthenticatedDomiciliosRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedKioskoRoute: AuthenticatedKioskoRoute,
  AuthenticatedLlevarRoute: AuthenticatedLlevarRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedPedidosOnlineRoute: AuthenticatedPedidosOnlineRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
  AuthenticatedMenuCategoriasRoute: AuthenticatedMenuCategoriasRoute,
  AuthenticatedMenuInsumosRoute: AuthenticatedMenuInsumosRoute,
  AuthenticatedMenuModificadoresRoute: AuthenticatedMenuModificadoresRoute,
  AuthenticatedMenuProductosRoute: AuthenticatedMenuProductosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KioskRoute: KioskRoute,
  MenuRoute: MenuRoute,
  TTableNumberRoute: TTableNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
