/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabletPedidosRouteImport } from './routes/tablet-pedidos'
import { Route as MisPuntosRouteImport } from './routes/mis-puntos'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as KdsLiveRouteImport } from './routes/kds-live'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTableNumberRouteImport } from './routes/t.$tableNumber'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedVentasRouteImport } from './routes/_authenticated/ventas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedTodosPedidosRouteImport } from './routes/_authenticated/todos-pedidos'
import { Route as AuthenticatedTiposGastoRouteImport } from './routes/_authenticated/tipos-gasto'
import { Route as AuthenticatedSugerenciasCompraRouteImport } from './routes/_authenticated/sugerencias-compra'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedRepartidoresRouteImport } from './routes/_authenticated/repartidores'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPedidosOnlineRouteImport } from './routes/_authenticated/pedidos-online'
import { Route as AuthenticatedOpinionesRouteImport } from './routes/_authenticated/opiniones'
import { Route as AuthenticatedMonitoreoRouteImport } from './routes/_authenticated/monitoreo'
import { Route as AuthenticatedMesasAdminRouteImport } from './routes/_authenticated/mesas-admin'
import { Route as AuthenticatedMesasRouteImport } from './routes/_authenticated/mesas'
import { Route as AuthenticatedLlevarPendientesRouteImport } from './routes/_authenticated/llevar-pendientes'
import { Route as AuthenticatedLlevarRouteImport } from './routes/_authenticated/llevar'
import { Route as AuthenticatedKioskoRouteImport } from './routes/_authenticated/kiosko'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated/kds'
import { Route as AuthenticatedInventarioRouteImport } from './routes/_authenticated/inventario'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated/historial'
import { Route as AuthenticatedGastosRouteImport } from './routes/_authenticated/gastos'
import { Route as AuthenticatedEstadisticasRouteImport } from './routes/_authenticated/estadisticas'
import { Route as AuthenticatedEgresosRouteImport } from './routes/_authenticated/egresos'
import { Route as AuthenticatedDomiciliosRouteImport } from './routes/_authenticated/domicilios'
import { Route as AuthenticatedDomicilioRouteImport } from './routes/_authenticated/domicilio'
import { Route as AuthenticatedDeudasRouteImport } from './routes/_authenticated/deudas'
import { Route as AuthenticatedDepositosRouteImport } from './routes/_authenticated/depositos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCajaRouteImport } from './routes/_authenticated/caja'
import { Route as AuthenticatedAyudaRouteImport } from './routes/_authenticated/ayuda'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAsistenciaRouteImport } from './routes/_authenticated/asistencia'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as SSlugIndexRouteImport } from './routes/s.$slug.index'
import { Route as AuthenticatedReportesIndexRouteImport } from './routes/_authenticated/reportes.index'
import { Route as SSlugMenuRouteImport } from './routes/s.$slug.menu'
import { Route as SSlugManifestDotwebmanifestRouteImport } from './routes/s.$slug.manifest[.]webmanifest'
import { Route as SSlugKioskRouteImport } from './routes/s.$slug.kiosk'
import { Route as AsistenciaTerminalSlugRouteImport } from './routes/asistencia.terminal.$slug'
import { Route as AuthenticatedReportesVentasRouteImport } from './routes/_authenticated/reportes.ventas'
import { Route as AuthenticatedReportesResumenRouteImport } from './routes/_authenticated/reportes.resumen'
import { Route as AuthenticatedReportesCajasRouteImport } from './routes/_authenticated/reportes.cajas'
import { Route as AuthenticatedReportesAuditoriaRouteImport } from './routes/_authenticated/reportes.auditoria'
import { Route as AuthenticatedMenuRecetasRouteImport } from './routes/_authenticated/menu/recetas'
import { Route as AuthenticatedMenuProductosRouteImport } from './routes/_authenticated/menu/productos'
import { Route as AuthenticatedMenuModificadoresRouteImport } from './routes/_authenticated/menu/modificadores'
import { Route as AuthenticatedMenuInsumosRouteImport } from './routes/_authenticated/menu/insumos'
import { Route as AuthenticatedMenuCategoriasRouteImport } from './routes/_authenticated/menu/categorias'
import { Route as SSlugTTableNumberRouteImport } from './routes/s.$slug.t.$tableNumber'
import { Route as AuthenticatedReportesCajasIdRouteImport } from './routes/_authenticated/reportes.cajas_.$id'

const TabletPedidosRoute = TabletPedidosRouteImport.update({
  id: '/tablet-pedidos',
  path: '/tablet-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPuntosRoute = MisPuntosRouteImport.update({
  id: '/mis-puntos',
  path: '/mis-puntos',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsLiveRoute = KdsLiveRouteImport.update({
  id: '/kds-live',
  path: '/kds-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableNumberRoute = TTableNumberRouteImport.update({
  id: '/t/$tableNumber',
  path: '/t/$tableNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVentasRoute = AuthenticatedVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodosPedidosRoute =
  AuthenticatedTodosPedidosRouteImport.update({
    id: '/todos-pedidos',
    path: '/todos-pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTiposGastoRoute = AuthenticatedTiposGastoRouteImport.update({
  id: '/tipos-gasto',
  path: '/tipos-gasto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSugerenciasCompraRoute =
  AuthenticatedSugerenciasCompraRouteImport.update({
    id: '/sugerencias-compra',
    path: '/sugerencias-compra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepartidoresRoute =
  AuthenticatedRepartidoresRouteImport.update({
    id: '/repartidores',
    path: '/repartidores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosOnlineRoute =
  AuthenticatedPedidosOnlineRouteImport.update({
    id: '/pedidos-online',
    path: '/pedidos-online',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpinionesRoute = AuthenticatedOpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoreoRoute = AuthenticatedMonitoreoRouteImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasAdminRoute = AuthenticatedMesasAdminRouteImport.update({
  id: '/mesas-admin',
  path: '/mesas-admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesasRoute = AuthenticatedMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLlevarPendientesRoute =
  AuthenticatedLlevarPendientesRouteImport.update({
    id: '/llevar-pendientes',
    path: '/llevar-pendientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLlevarRoute = AuthenticatedLlevarRouteImport.update({
  id: '/llevar',
  path: '/llevar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKioskoRoute = AuthenticatedKioskoRouteImport.update({
  id: '/kiosko',
  path: '/kiosko',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarioRoute = AuthenticatedInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGastosRoute = AuthenticatedGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstadisticasRoute =
  AuthenticatedEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEgresosRoute = AuthenticatedEgresosRouteImport.update({
  id: '/egresos',
  path: '/egresos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomiciliosRoute = AuthenticatedDomiciliosRouteImport.update({
  id: '/domicilios',
  path: '/domicilios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDomicilioRoute = AuthenticatedDomicilioRouteImport.update({
  id: '/domicilio',
  path: '/domicilio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeudasRoute = AuthenticatedDeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositosRoute = AuthenticatedDepositosRouteImport.update({
  id: '/depositos',
  path: '/depositos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCajaRoute = AuthenticatedCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAyudaRoute = AuthenticatedAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsistenciaRoute = AuthenticatedAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SSlugIndexRoute = SSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedReportesIndexRoute =
  AuthenticatedReportesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const SSlugMenuRoute = SSlugMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => SSlugRoute,
} as any)
const SSlugManifestDotwebmanifestRoute =
  SSlugManifestDotwebmanifestRouteImport.update({
    id: '/manifest.webmanifest',
    path: '/manifest.webmanifest',
    getParentRoute: () => SSlugRoute,
  } as any)
const SSlugKioskRoute = SSlugKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => SSlugRoute,
} as any)
const AsistenciaTerminalSlugRoute = AsistenciaTerminalSlugRouteImport.update({
  id: '/asistencia/terminal/$slug',
  path: '/asistencia/terminal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportesVentasRoute =
  AuthenticatedReportesVentasRouteImport.update({
    id: '/ventas',
    path: '/ventas',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesResumenRoute =
  AuthenticatedReportesResumenRouteImport.update({
    id: '/resumen',
    path: '/resumen',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesCajasRoute =
  AuthenticatedReportesCajasRouteImport.update({
    id: '/cajas',
    path: '/cajas',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedReportesAuditoriaRoute =
  AuthenticatedReportesAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)
const AuthenticatedMenuRecetasRoute =
  AuthenticatedMenuRecetasRouteImport.update({
    id: '/menu/recetas',
    path: '/menu/recetas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuProductosRoute =
  AuthenticatedMenuProductosRouteImport.update({
    id: '/menu/productos',
    path: '/menu/productos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuModificadoresRoute =
  AuthenticatedMenuModificadoresRouteImport.update({
    id: '/menu/modificadores',
    path: '/menu/modificadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuInsumosRoute =
  AuthenticatedMenuInsumosRouteImport.update({
    id: '/menu/insumos',
    path: '/menu/insumos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuCategoriasRoute =
  AuthenticatedMenuCategoriasRouteImport.update({
    id: '/menu/categorias',
    path: '/menu/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SSlugTTableNumberRoute = SSlugTTableNumberRouteImport.update({
  id: '/t/$tableNumber',
  path: '/t/$tableNumber',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedReportesCajasIdRoute =
  AuthenticatedReportesCajasIdRouteImport.update({
    id: '/cajas_/$id',
    path: '/cajas/$id',
    getParentRoute: () => AuthenticatedReportesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kds-live': typeof KdsLiveRoute
  '/kiosk': typeof KioskRoute
  '/menu': typeof MenuRoute
  '/mis-puntos': typeof MisPuntosRoute
  '/tablet-pedidos': typeof TabletPedidosRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/ayuda': typeof AuthenticatedAyudaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depositos': typeof AuthenticatedDepositosRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/domicilio': typeof AuthenticatedDomicilioRoute
  '/domicilios': typeof AuthenticatedDomiciliosRoute
  '/egresos': typeof AuthenticatedEgresosRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/kiosko': typeof AuthenticatedKioskoRoute
  '/llevar': typeof AuthenticatedLlevarRoute
  '/llevar-pendientes': typeof AuthenticatedLlevarPendientesRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/mesas-admin': typeof AuthenticatedMesasAdminRoute
  '/monitoreo': typeof AuthenticatedMonitoreoRoute
  '/opiniones': typeof AuthenticatedOpinionesRoute
  '/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/pos': typeof AuthenticatedPosRoute
  '/repartidores': typeof AuthenticatedRepartidoresRoute
  '/reportes': typeof AuthenticatedReportesRouteWithChildren
  '/sugerencias-compra': typeof AuthenticatedSugerenciasCompraRoute
  '/tipos-gasto': typeof AuthenticatedTiposGastoRoute
  '/todos-pedidos': typeof AuthenticatedTodosPedidosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/t/$tableNumber': typeof TTableNumberRoute
  '/menu/categorias': typeof AuthenticatedMenuCategoriasRoute
  '/menu/insumos': typeof AuthenticatedMenuInsumosRoute
  '/menu/modificadores': typeof AuthenticatedMenuModificadoresRoute
  '/menu/productos': typeof AuthenticatedMenuProductosRoute
  '/menu/recetas': typeof AuthenticatedMenuRecetasRoute
  '/reportes/auditoria': typeof AuthenticatedReportesAuditoriaRoute
  '/reportes/cajas': typeof AuthenticatedReportesCajasRoute
  '/reportes/resumen': typeof AuthenticatedReportesResumenRoute
  '/reportes/ventas': typeof AuthenticatedReportesVentasRoute
  '/asistencia/terminal/$slug': typeof AsistenciaTerminalSlugRoute
  '/s/$slug/kiosk': typeof SSlugKioskRoute
  '/s/$slug/manifest.webmanifest': typeof SSlugManifestDotwebmanifestRoute
  '/s/$slug/menu': typeof SSlugMenuRoute
  '/reportes/': typeof AuthenticatedReportesIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/reportes/cajas/$id': typeof AuthenticatedReportesCajasIdRoute
  '/s/$slug/t/$tableNumber': typeof SSlugTTableNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kds-live': typeof KdsLiveRoute
  '/kiosk': typeof KioskRoute
  '/menu': typeof MenuRoute
  '/mis-puntos': typeof MisPuntosRoute
  '/tablet-pedidos': typeof TabletPedidosRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/asistencia': typeof AuthenticatedAsistenciaRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/ayuda': typeof AuthenticatedAyudaRoute
  '/caja': typeof AuthenticatedCajaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/depositos': typeof AuthenticatedDepositosRoute
  '/deudas': typeof AuthenticatedDeudasRoute
  '/domicilio': typeof AuthenticatedDomicilioRoute
  '/domicilios': typeof AuthenticatedDomiciliosRoute
  '/egresos': typeof AuthenticatedEgresosRoute
  '/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/gastos': typeof AuthenticatedGastosRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/inventario': typeof AuthenticatedInventarioRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/kiosko': typeof AuthenticatedKioskoRoute
  '/llevar': typeof AuthenticatedLlevarRoute
  '/llevar-pendientes': typeof AuthenticatedLlevarPendientesRoute
  '/mesas': typeof AuthenticatedMesasRoute
  '/mesas-admin': typeof AuthenticatedMesasAdminRoute
  '/monitoreo': typeof AuthenticatedMonitoreoRoute
  '/opiniones': typeof AuthenticatedOpinionesRoute
  '/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/pos': typeof AuthenticatedPosRoute
  '/repartidores': typeof AuthenticatedRepartidoresRoute
  '/sugerencias-compra': typeof AuthenticatedSugerenciasCompraRoute
  '/tipos-gasto': typeof AuthenticatedTiposGastoRoute
  '/todos-pedidos': typeof AuthenticatedTodosPedidosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ventas': typeof AuthenticatedVentasRoute
  '/t/$tableNumber': typeof TTableNumberRoute
  '/menu/categorias': typeof AuthenticatedMenuCategoriasRoute
  '/menu/insumos': typeof AuthenticatedMenuInsumosRoute
  '/menu/modificadores': typeof AuthenticatedMenuModificadoresRoute
  '/menu/productos': typeof AuthenticatedMenuProductosRoute
  '/menu/recetas': typeof AuthenticatedMenuRecetasRoute
  '/reportes/auditoria': typeof AuthenticatedReportesAuditoriaRoute
  '/reportes/cajas': typeof AuthenticatedReportesCajasRoute
  '/reportes/resumen': typeof AuthenticatedReportesResumenRoute
  '/reportes/ventas': typeof AuthenticatedReportesVentasRoute
  '/asistencia/terminal/$slug': typeof AsistenciaTerminalSlugRoute
  '/s/$slug/kiosk': typeof SSlugKioskRoute
  '/s/$slug/manifest.webmanifest': typeof SSlugManifestDotwebmanifestRoute
  '/s/$slug/menu': typeof SSlugMenuRoute
  '/reportes': typeof AuthenticatedReportesIndexRoute
  '/s/$slug': typeof SSlugIndexRoute
  '/reportes/cajas/$id': typeof AuthenticatedReportesCajasIdRoute
  '/s/$slug/t/$tableNumber': typeof SSlugTTableNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/kds-live': typeof KdsLiveRoute
  '/kiosk': typeof KioskRoute
  '/menu': typeof MenuRoute
  '/mis-puntos': typeof MisPuntosRoute
  '/tablet-pedidos': typeof TabletPedidosRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/asistencia': typeof AuthenticatedAsistenciaRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/ayuda': typeof AuthenticatedAyudaRoute
  '/_authenticated/caja': typeof AuthenticatedCajaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/depositos': typeof AuthenticatedDepositosRoute
  '/_authenticated/deudas': typeof AuthenticatedDeudasRoute
  '/_authenticated/domicilio': typeof AuthenticatedDomicilioRoute
  '/_authenticated/domicilios': typeof AuthenticatedDomiciliosRoute
  '/_authenticated/egresos': typeof AuthenticatedEgresosRoute
  '/_authenticated/estadisticas': typeof AuthenticatedEstadisticasRoute
  '/_authenticated/gastos': typeof AuthenticatedGastosRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/inventario': typeof AuthenticatedInventarioRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/kiosko': typeof AuthenticatedKioskoRoute
  '/_authenticated/llevar': typeof AuthenticatedLlevarRoute
  '/_authenticated/llevar-pendientes': typeof AuthenticatedLlevarPendientesRoute
  '/_authenticated/mesas': typeof AuthenticatedMesasRoute
  '/_authenticated/mesas-admin': typeof AuthenticatedMesasAdminRoute
  '/_authenticated/monitoreo': typeof AuthenticatedMonitoreoRoute
  '/_authenticated/opiniones': typeof AuthenticatedOpinionesRoute
  '/_authenticated/pedidos-online': typeof AuthenticatedPedidosOnlineRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/repartidores': typeof AuthenticatedRepartidoresRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRouteWithChildren
  '/_authenticated/sugerencias-compra': typeof AuthenticatedSugerenciasCompraRoute
  '/_authenticated/tipos-gasto': typeof AuthenticatedTiposGastoRoute
  '/_authenticated/todos-pedidos': typeof AuthenticatedTodosPedidosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ventas': typeof AuthenticatedVentasRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/t/$tableNumber': typeof TTableNumberRoute
  '/_authenticated/menu/categorias': typeof AuthenticatedMenuCategoriasRoute
  '/_authenticated/menu/insumos': typeof AuthenticatedMenuInsumosRoute
  '/_authenticated/menu/modificadores': typeof AuthenticatedMenuModificadoresRoute
  '/_authenticated/menu/productos': typeof AuthenticatedMenuProductosRoute
  '/_authenticated/menu/recetas': typeof AuthenticatedMenuRecetasRoute
  '/_authenticated/reportes/auditoria': typeof AuthenticatedReportesAuditoriaRoute
  '/_authenticated/reportes/cajas': typeof AuthenticatedReportesCajasRoute
  '/_authenticated/reportes/resumen': typeof AuthenticatedReportesResumenRoute
  '/_authenticated/reportes/ventas': typeof AuthenticatedReportesVentasRoute
  '/asistencia/terminal/$slug': typeof AsistenciaTerminalSlugRoute
  '/s/$slug/kiosk': typeof SSlugKioskRoute
  '/s/$slug/manifest.webmanifest': typeof SSlugManifestDotwebmanifestRoute
  '/s/$slug/menu': typeof SSlugMenuRoute
  '/_authenticated/reportes/': typeof AuthenticatedReportesIndexRoute
  '/s/$slug/': typeof SSlugIndexRoute
  '/_authenticated/reportes/cajas_/$id': typeof AuthenticatedReportesCajasIdRoute
  '/s/$slug/t/$tableNumber': typeof SSlugTTableNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kds-live'
    | '/kiosk'
    | '/menu'
    | '/mis-puntos'
    | '/tablet-pedidos'
    | '/ajustes'
    | '/asistencia'
    | '/auditoria'
    | '/ayuda'
    | '/caja'
    | '/clientes'
    | '/compras'
    | '/crm'
    | '/dashboard'
    | '/depositos'
    | '/deudas'
    | '/domicilio'
    | '/domicilios'
    | '/egresos'
    | '/estadisticas'
    | '/gastos'
    | '/historial'
    | '/inventario'
    | '/kds'
    | '/kiosko'
    | '/llevar'
    | '/llevar-pendientes'
    | '/mesas'
    | '/mesas-admin'
    | '/monitoreo'
    | '/opiniones'
    | '/pedidos-online'
    | '/pos'
    | '/repartidores'
    | '/reportes'
    | '/sugerencias-compra'
    | '/tipos-gasto'
    | '/todos-pedidos'
    | '/usuarios'
    | '/ventas'
    | '/s/$slug'
    | '/t/$tableNumber'
    | '/menu/categorias'
    | '/menu/insumos'
    | '/menu/modificadores'
    | '/menu/productos'
    | '/menu/recetas'
    | '/reportes/auditoria'
    | '/reportes/cajas'
    | '/reportes/resumen'
    | '/reportes/ventas'
    | '/asistencia/terminal/$slug'
    | '/s/$slug/kiosk'
    | '/s/$slug/manifest.webmanifest'
    | '/s/$slug/menu'
    | '/reportes/'
    | '/s/$slug/'
    | '/reportes/cajas/$id'
    | '/s/$slug/t/$tableNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kds-live'
    | '/kiosk'
    | '/menu'
    | '/mis-puntos'
    | '/tablet-pedidos'
    | '/ajustes'
    | '/asistencia'
    | '/auditoria'
    | '/ayuda'
    | '/caja'
    | '/clientes'
    | '/compras'
    | '/crm'
    | '/dashboard'
    | '/depositos'
    | '/deudas'
    | '/domicilio'
    | '/domicilios'
    | '/egresos'
    | '/estadisticas'
    | '/gastos'
    | '/historial'
    | '/inventario'
    | '/kds'
    | '/kiosko'
    | '/llevar'
    | '/llevar-pendientes'
    | '/mesas'
    | '/mesas-admin'
    | '/monitoreo'
    | '/opiniones'
    | '/pedidos-online'
    | '/pos'
    | '/repartidores'
    | '/sugerencias-compra'
    | '/tipos-gasto'
    | '/todos-pedidos'
    | '/usuarios'
    | '/ventas'
    | '/t/$tableNumber'
    | '/menu/categorias'
    | '/menu/insumos'
    | '/menu/modificadores'
    | '/menu/productos'
    | '/menu/recetas'
    | '/reportes/auditoria'
    | '/reportes/cajas'
    | '/reportes/resumen'
    | '/reportes/ventas'
    | '/asistencia/terminal/$slug'
    | '/s/$slug/kiosk'
    | '/s/$slug/manifest.webmanifest'
    | '/s/$slug/menu'
    | '/reportes'
    | '/s/$slug'
    | '/reportes/cajas/$id'
    | '/s/$slug/t/$tableNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/kds-live'
    | '/kiosk'
    | '/menu'
    | '/mis-puntos'
    | '/tablet-pedidos'
    | '/_authenticated/ajustes'
    | '/_authenticated/asistencia'
    | '/_authenticated/auditoria'
    | '/_authenticated/ayuda'
    | '/_authenticated/caja'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/depositos'
    | '/_authenticated/deudas'
    | '/_authenticated/domicilio'
    | '/_authenticated/domicilios'
    | '/_authenticated/egresos'
    | '/_authenticated/estadisticas'
    | '/_authenticated/gastos'
    | '/_authenticated/historial'
    | '/_authenticated/inventario'
    | '/_authenticated/kds'
    | '/_authenticated/kiosko'
    | '/_authenticated/llevar'
    | '/_authenticated/llevar-pendientes'
    | '/_authenticated/mesas'
    | '/_authenticated/mesas-admin'
    | '/_authenticated/monitoreo'
    | '/_authenticated/opiniones'
    | '/_authenticated/pedidos-online'
    | '/_authenticated/pos'
    | '/_authenticated/repartidores'
    | '/_authenticated/reportes'
    | '/_authenticated/sugerencias-compra'
    | '/_authenticated/tipos-gasto'
    | '/_authenticated/todos-pedidos'
    | '/_authenticated/usuarios'
    | '/_authenticated/ventas'
    | '/s/$slug'
    | '/t/$tableNumber'
    | '/_authenticated/menu/categorias'
    | '/_authenticated/menu/insumos'
    | '/_authenticated/menu/modificadores'
    | '/_authenticated/menu/productos'
    | '/_authenticated/menu/recetas'
    | '/_authenticated/reportes/auditoria'
    | '/_authenticated/reportes/cajas'
    | '/_authenticated/reportes/resumen'
    | '/_authenticated/reportes/ventas'
    | '/asistencia/terminal/$slug'
    | '/s/$slug/kiosk'
    | '/s/$slug/manifest.webmanifest'
    | '/s/$slug/menu'
    | '/_authenticated/reportes/'
    | '/s/$slug/'
    | '/_authenticated/reportes/cajas_/$id'
    | '/s/$slug/t/$tableNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KdsLiveRoute: typeof KdsLiveRoute
  KioskRoute: typeof KioskRoute
  MenuRoute: typeof MenuRoute
  MisPuntosRoute: typeof MisPuntosRoute
  TabletPedidosRoute: typeof TabletPedidosRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  TTableNumberRoute: typeof TTableNumberRoute
  AsistenciaTerminalSlugRoute: typeof AsistenciaTerminalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablet-pedidos': {
      id: '/tablet-pedidos'
      path: '/tablet-pedidos'
      fullPath: '/tablet-pedidos'
      preLoaderRoute: typeof TabletPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-puntos': {
      id: '/mis-puntos'
      path: '/mis-puntos'
      fullPath: '/mis-puntos'
      preLoaderRoute: typeof MisPuntosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kds-live': {
      id: '/kds-live'
      path: '/kds-live'
      fullPath: '/kds-live'
      preLoaderRoute: typeof KdsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableNumber': {
      id: '/t/$tableNumber'
      path: '/t/$tableNumber'
      fullPath: '/t/$tableNumber'
      preLoaderRoute: typeof TTableNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ventas': {
      id: '/_authenticated/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthenticatedVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/todos-pedidos': {
      id: '/_authenticated/todos-pedidos'
      path: '/todos-pedidos'
      fullPath: '/todos-pedidos'
      preLoaderRoute: typeof AuthenticatedTodosPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tipos-gasto': {
      id: '/_authenticated/tipos-gasto'
      path: '/tipos-gasto'
      fullPath: '/tipos-gasto'
      preLoaderRoute: typeof AuthenticatedTiposGastoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sugerencias-compra': {
      id: '/_authenticated/sugerencias-compra'
      path: '/sugerencias-compra'
      fullPath: '/sugerencias-compra'
      preLoaderRoute: typeof AuthenticatedSugerenciasCompraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repartidores': {
      id: '/_authenticated/repartidores'
      path: '/repartidores'
      fullPath: '/repartidores'
      preLoaderRoute: typeof AuthenticatedRepartidoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos-online': {
      id: '/_authenticated/pedidos-online'
      path: '/pedidos-online'
      fullPath: '/pedidos-online'
      preLoaderRoute: typeof AuthenticatedPedidosOnlineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opiniones': {
      id: '/_authenticated/opiniones'
      path: '/opiniones'
      fullPath: '/opiniones'
      preLoaderRoute: typeof AuthenticatedOpinionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoreo': {
      id: '/_authenticated/monitoreo'
      path: '/monitoreo'
      fullPath: '/monitoreo'
      preLoaderRoute: typeof AuthenticatedMonitoreoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas-admin': {
      id: '/_authenticated/mesas-admin'
      path: '/mesas-admin'
      fullPath: '/mesas-admin'
      preLoaderRoute: typeof AuthenticatedMesasAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mesas': {
      id: '/_authenticated/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AuthenticatedMesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/llevar-pendientes': {
      id: '/_authenticated/llevar-pendientes'
      path: '/llevar-pendientes'
      fullPath: '/llevar-pendientes'
      preLoaderRoute: typeof AuthenticatedLlevarPendientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/llevar': {
      id: '/_authenticated/llevar'
      path: '/llevar'
      fullPath: '/llevar'
      preLoaderRoute: typeof AuthenticatedLlevarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kiosko': {
      id: '/_authenticated/kiosko'
      path: '/kiosko'
      fullPath: '/kiosko'
      preLoaderRoute: typeof AuthenticatedKioskoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventario': {
      id: '/_authenticated/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AuthenticatedInventarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gastos': {
      id: '/_authenticated/gastos'
      path: '/gastos'
      fullPath: '/gastos'
      preLoaderRoute: typeof AuthenticatedGastosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estadisticas': {
      id: '/_authenticated/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AuthenticatedEstadisticasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/egresos': {
      id: '/_authenticated/egresos'
      path: '/egresos'
      fullPath: '/egresos'
      preLoaderRoute: typeof AuthenticatedEgresosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domicilios': {
      id: '/_authenticated/domicilios'
      path: '/domicilios'
      fullPath: '/domicilios'
      preLoaderRoute: typeof AuthenticatedDomiciliosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domicilio': {
      id: '/_authenticated/domicilio'
      path: '/domicilio'
      fullPath: '/domicilio'
      preLoaderRoute: typeof AuthenticatedDomicilioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deudas': {
      id: '/_authenticated/deudas'
      path: '/deudas'
      fullPath: '/deudas'
      preLoaderRoute: typeof AuthenticatedDeudasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/depositos': {
      id: '/_authenticated/depositos'
      path: '/depositos'
      fullPath: '/depositos'
      preLoaderRoute: typeof AuthenticatedDepositosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caja': {
      id: '/_authenticated/caja'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof AuthenticatedCajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ayuda': {
      id: '/_authenticated/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AuthenticatedAyudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistencia': {
      id: '/_authenticated/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AuthenticatedAsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/': {
      id: '/s/$slug/'
      path: '/'
      fullPath: '/s/$slug/'
      preLoaderRoute: typeof SSlugIndexRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/reportes/': {
      id: '/_authenticated/reportes/'
      path: '/'
      fullPath: '/reportes/'
      preLoaderRoute: typeof AuthenticatedReportesIndexRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/s/$slug/menu': {
      id: '/s/$slug/menu'
      path: '/menu'
      fullPath: '/s/$slug/menu'
      preLoaderRoute: typeof SSlugMenuRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/manifest.webmanifest': {
      id: '/s/$slug/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/s/$slug/manifest.webmanifest'
      preLoaderRoute: typeof SSlugManifestDotwebmanifestRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/s/$slug/kiosk': {
      id: '/s/$slug/kiosk'
      path: '/kiosk'
      fullPath: '/s/$slug/kiosk'
      preLoaderRoute: typeof SSlugKioskRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/asistencia/terminal/$slug': {
      id: '/asistencia/terminal/$slug'
      path: '/asistencia/terminal/$slug'
      fullPath: '/asistencia/terminal/$slug'
      preLoaderRoute: typeof AsistenciaTerminalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reportes/ventas': {
      id: '/_authenticated/reportes/ventas'
      path: '/ventas'
      fullPath: '/reportes/ventas'
      preLoaderRoute: typeof AuthenticatedReportesVentasRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/resumen': {
      id: '/_authenticated/reportes/resumen'
      path: '/resumen'
      fullPath: '/reportes/resumen'
      preLoaderRoute: typeof AuthenticatedReportesResumenRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/cajas': {
      id: '/_authenticated/reportes/cajas'
      path: '/cajas'
      fullPath: '/reportes/cajas'
      preLoaderRoute: typeof AuthenticatedReportesCajasRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/reportes/auditoria': {
      id: '/_authenticated/reportes/auditoria'
      path: '/auditoria'
      fullPath: '/reportes/auditoria'
      preLoaderRoute: typeof AuthenticatedReportesAuditoriaRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
    '/_authenticated/menu/recetas': {
      id: '/_authenticated/menu/recetas'
      path: '/menu/recetas'
      fullPath: '/menu/recetas'
      preLoaderRoute: typeof AuthenticatedMenuRecetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/productos': {
      id: '/_authenticated/menu/productos'
      path: '/menu/productos'
      fullPath: '/menu/productos'
      preLoaderRoute: typeof AuthenticatedMenuProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/modificadores': {
      id: '/_authenticated/menu/modificadores'
      path: '/menu/modificadores'
      fullPath: '/menu/modificadores'
      preLoaderRoute: typeof AuthenticatedMenuModificadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/insumos': {
      id: '/_authenticated/menu/insumos'
      path: '/menu/insumos'
      fullPath: '/menu/insumos'
      preLoaderRoute: typeof AuthenticatedMenuInsumosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/categorias': {
      id: '/_authenticated/menu/categorias'
      path: '/menu/categorias'
      fullPath: '/menu/categorias'
      preLoaderRoute: typeof AuthenticatedMenuCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$slug/t/$tableNumber': {
      id: '/s/$slug/t/$tableNumber'
      path: '/t/$tableNumber'
      fullPath: '/s/$slug/t/$tableNumber'
      preLoaderRoute: typeof SSlugTTableNumberRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/reportes/cajas_/$id': {
      id: '/_authenticated/reportes/cajas_/$id'
      path: '/cajas/$id'
      fullPath: '/reportes/cajas/$id'
      preLoaderRoute: typeof AuthenticatedReportesCajasIdRouteImport
      parentRoute: typeof AuthenticatedReportesRoute
    }
  }
}

interface AuthenticatedReportesRouteChildren {
  AuthenticatedReportesAuditoriaRoute: typeof AuthenticatedReportesAuditoriaRoute
  AuthenticatedReportesCajasRoute: typeof AuthenticatedReportesCajasRoute
  AuthenticatedReportesResumenRoute: typeof AuthenticatedReportesResumenRoute
  AuthenticatedReportesVentasRoute: typeof AuthenticatedReportesVentasRoute
  AuthenticatedReportesIndexRoute: typeof AuthenticatedReportesIndexRoute
  AuthenticatedReportesCajasIdRoute: typeof AuthenticatedReportesCajasIdRoute
}

const AuthenticatedReportesRouteChildren: AuthenticatedReportesRouteChildren = {
  AuthenticatedReportesAuditoriaRoute: AuthenticatedReportesAuditoriaRoute,
  AuthenticatedReportesCajasRoute: AuthenticatedReportesCajasRoute,
  AuthenticatedReportesResumenRoute: AuthenticatedReportesResumenRoute,
  AuthenticatedReportesVentasRoute: AuthenticatedReportesVentasRoute,
  AuthenticatedReportesIndexRoute: AuthenticatedReportesIndexRoute,
  AuthenticatedReportesCajasIdRoute: AuthenticatedReportesCajasIdRoute,
}

const AuthenticatedReportesRouteWithChildren =
  AuthenticatedReportesRoute._addFileChildren(
    AuthenticatedReportesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedAsistenciaRoute: typeof AuthenticatedAsistenciaRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedAyudaRoute: typeof AuthenticatedAyudaRoute
  AuthenticatedCajaRoute: typeof AuthenticatedCajaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositosRoute: typeof AuthenticatedDepositosRoute
  AuthenticatedDeudasRoute: typeof AuthenticatedDeudasRoute
  AuthenticatedDomicilioRoute: typeof AuthenticatedDomicilioRoute
  AuthenticatedDomiciliosRoute: typeof AuthenticatedDomiciliosRoute
  AuthenticatedEgresosRoute: typeof AuthenticatedEgresosRoute
  AuthenticatedEstadisticasRoute: typeof AuthenticatedEstadisticasRoute
  AuthenticatedGastosRoute: typeof AuthenticatedGastosRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedInventarioRoute: typeof AuthenticatedInventarioRoute
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedKioskoRoute: typeof AuthenticatedKioskoRoute
  AuthenticatedLlevarRoute: typeof AuthenticatedLlevarRoute
  AuthenticatedLlevarPendientesRoute: typeof AuthenticatedLlevarPendientesRoute
  AuthenticatedMesasRoute: typeof AuthenticatedMesasRoute
  AuthenticatedMesasAdminRoute: typeof AuthenticatedMesasAdminRoute
  AuthenticatedMonitoreoRoute: typeof AuthenticatedMonitoreoRoute
  AuthenticatedOpinionesRoute: typeof AuthenticatedOpinionesRoute
  AuthenticatedPedidosOnlineRoute: typeof AuthenticatedPedidosOnlineRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedRepartidoresRoute: typeof AuthenticatedRepartidoresRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRouteWithChildren
  AuthenticatedSugerenciasCompraRoute: typeof AuthenticatedSugerenciasCompraRoute
  AuthenticatedTiposGastoRoute: typeof AuthenticatedTiposGastoRoute
  AuthenticatedTodosPedidosRoute: typeof AuthenticatedTodosPedidosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedVentasRoute: typeof AuthenticatedVentasRoute
  AuthenticatedMenuCategoriasRoute: typeof AuthenticatedMenuCategoriasRoute
  AuthenticatedMenuInsumosRoute: typeof AuthenticatedMenuInsumosRoute
  AuthenticatedMenuModificadoresRoute: typeof AuthenticatedMenuModificadoresRoute
  AuthenticatedMenuProductosRoute: typeof AuthenticatedMenuProductosRoute
  AuthenticatedMenuRecetasRoute: typeof AuthenticatedMenuRecetasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedAsistenciaRoute: AuthenticatedAsistenciaRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedAyudaRoute: AuthenticatedAyudaRoute,
  AuthenticatedCajaRoute: AuthenticatedCajaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositosRoute: AuthenticatedDepositosRoute,
  AuthenticatedDeudasRoute: AuthenticatedDeudasRoute,
  AuthenticatedDomicilioRoute: AuthenticatedDomicilioRoute,
  AuthenticatedDomiciliosRoute: AuthenticatedDomiciliosRoute,
  AuthenticatedEgresosRoute: AuthenticatedEgresosRoute,
  AuthenticatedEstadisticasRoute: AuthenticatedEstadisticasRoute,
  AuthenticatedGastosRoute: AuthenticatedGastosRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedInventarioRoute: AuthenticatedInventarioRoute,
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedKioskoRoute: AuthenticatedKioskoRoute,
  AuthenticatedLlevarRoute: AuthenticatedLlevarRoute,
  AuthenticatedLlevarPendientesRoute: AuthenticatedLlevarPendientesRoute,
  AuthenticatedMesasRoute: AuthenticatedMesasRoute,
  AuthenticatedMesasAdminRoute: AuthenticatedMesasAdminRoute,
  AuthenticatedMonitoreoRoute: AuthenticatedMonitoreoRoute,
  AuthenticatedOpinionesRoute: AuthenticatedOpinionesRoute,
  AuthenticatedPedidosOnlineRoute: AuthenticatedPedidosOnlineRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedRepartidoresRoute: AuthenticatedRepartidoresRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRouteWithChildren,
  AuthenticatedSugerenciasCompraRoute: AuthenticatedSugerenciasCompraRoute,
  AuthenticatedTiposGastoRoute: AuthenticatedTiposGastoRoute,
  AuthenticatedTodosPedidosRoute: AuthenticatedTodosPedidosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedVentasRoute: AuthenticatedVentasRoute,
  AuthenticatedMenuCategoriasRoute: AuthenticatedMenuCategoriasRoute,
  AuthenticatedMenuInsumosRoute: AuthenticatedMenuInsumosRoute,
  AuthenticatedMenuModificadoresRoute: AuthenticatedMenuModificadoresRoute,
  AuthenticatedMenuProductosRoute: AuthenticatedMenuProductosRoute,
  AuthenticatedMenuRecetasRoute: AuthenticatedMenuRecetasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SSlugRouteChildren {
  SSlugKioskRoute: typeof SSlugKioskRoute
  SSlugManifestDotwebmanifestRoute: typeof SSlugManifestDotwebmanifestRoute
  SSlugMenuRoute: typeof SSlugMenuRoute
  SSlugIndexRoute: typeof SSlugIndexRoute
  SSlugTTableNumberRoute: typeof SSlugTTableNumberRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugKioskRoute: SSlugKioskRoute,
  SSlugManifestDotwebmanifestRoute: SSlugManifestDotwebmanifestRoute,
  SSlugMenuRoute: SSlugMenuRoute,
  SSlugIndexRoute: SSlugIndexRoute,
  SSlugTTableNumberRoute: SSlugTTableNumberRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KdsLiveRoute: KdsLiveRoute,
  KioskRoute: KioskRoute,
  MenuRoute: MenuRoute,
  MisPuntosRoute: MisPuntosRoute,
  TabletPedidosRoute: TabletPedidosRoute,
  SSlugRoute: SSlugRouteWithChildren,
  TTableNumberRoute: TTableNumberRoute,
  AsistenciaTerminalSlugRoute: AsistenciaTerminalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
