ALTER TABLE public.settings ADD COLUMN IF NOT EXISTS ticket_config JSONB NOT NULL DEFAULT '{
  "show_logo": true,
  "show_business_name": true,
  "show_nit": true,
  "show_address": true,
  "show_phone": true,
  "show_email": true,
  "show_ticket_number": true,
  "show_date": true,
  "show_customer": true,
  "show_customer_address": true,
  "show_customer_phone": true,
  "show_payment_method": true,
  "show_subtotal": true,
  "show_tax": true,
  "show_delivery_fee": true,
  "show_cash_received": true,
  "show_thanks": true,
  "show_decorations": true,
  "title_text": "TICKET DE VENTA",
  "number_prefix": "TV-",
  "thanks_text": "¡Gracias por Preferirnos!",
  "extra_footer": ""
}'::jsonb;